// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * Shade Framework - Groth16 Verifier
 * Generated by Shade Framework
 *
 * This verifier can be used to verify Groth16 proofs on-chain
 */

library Pairing {
    struct G1Point {
        uint X;
        uint Y;
    }

    // Encoding of field elements is: X[0] * z + X[1]
    struct G2Point {
        uint[2] X;
        uint[2] Y;
    }

    /// @return the generator of G1
    function P1() internal pure returns (G1Point memory) {
        return G1Point(1, 2);
    }

    /// @return the generator of G2
    function P2() internal pure returns (G2Point memory) {
        return G2Point(
            [11559732032986387107991004021392285783925812861821192530917403151452391805634,
             10857046999023057135944570762232829481370756359578518086990519993285655852781],
            [4082367875863433681332203403145435568316851327593401208105741076214120093531,
             8495653923123431417604973247489272438418190587263600148770280649306958101930]
        );
    }

    /// @return the negation of p, i.e. p.addition(p.negate()) should be zero.
    function negate(G1Point memory p) internal pure returns (G1Point memory) {
        // The prime q in the base field F_q for G1
        uint q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
        if (p.X == 0 && p.Y == 0)
            return G1Point(0, 0);
        return G1Point(p.X, q - (p.Y % q));
    }

    /// @return r the sum of two points of G1
    function addition(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {
        uint[4] memory input;
        input[0] = p1.X;
        input[1] = p1.Y;
        input[2] = p2.X;
        input[3] = p2.Y;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 6, input, 0xc0, r, 0x60)
        }
        require(success, "pairing-add-failed");
    }

    /// @return r the product of a point on G1 and a scalar, i.e.
    /// p == p.scalar_mul(1) and p.addition(p) == p.scalar_mul(2) for all points p.
    function scalar_mul(G1Point memory p, uint s) internal view returns (G1Point memory r) {
        uint[3] memory input;
        input[0] = p.X;
        input[1] = p.Y;
        input[2] = s;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 7, input, 0x80, r, 0x60)
        }
        require(success, "pairing-mul-failed");
    }

    /// @return the result of computing the pairing check
    /// e(p1[0], p2[0]) *  .... * e(p1[n], p2[n]) == 1
    /// For example pairing([P1(), P1().negate()], [P2(), P2()]) should return true.
    function pairing(G1Point[] memory p1, G2Point[] memory p2) internal view returns (bool) {
        require(p1.length == p2.length, "pairing-lengths-failed");
        uint elements = p1.length;
        uint inputSize = elements * 6;
        uint[] memory input = new uint[](inputSize);
        for (uint i = 0; i < elements; i++) {
            input[i * 6 + 0] = p1[i].X;
            input[i * 6 + 1] = p1[i].Y;
            input[i * 6 + 2] = p2[i].X[0];
            input[i * 6 + 3] = p2[i].X[1];
            input[i * 6 + 4] = p2[i].Y[0];
            input[i * 6 + 5] = p2[i].Y[1];
        }
        uint[1] memory out;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 8, add(input, 0x20), mul(inputSize, 0x20), out, 0x20)
        }
        require(success, "pairing-opcode-failed");
        return out[0] != 0;
    }

    /// Convenience method for a pairing check for two pairs.
    function pairingProd2(G1Point memory a1, G2Point memory a2, G1Point memory b1, G2Point memory b2) internal view returns (bool) {
        G1Point[] memory p1 = new G1Point[](2);
        G2Point[] memory p2 = new G2Point[](2);
        p1[0] = a1;
        p1[1] = b1;
        p2[0] = a2;
        p2[1] = b2;
        return pairing(p1, p2);
    }

    /// Convenience method for a pairing check for three pairs.
    function pairingProd3(
            G1Point memory a1, G2Point memory a2,
            G1Point memory b1, G2Point memory b2,
            G1Point memory c1, G2Point memory c2
    ) internal view returns (bool) {
        G1Point[] memory p1 = new G1Point[](3);
        G2Point[] memory p2 = new G2Point[](3);
        p1[0] = a1;
        p1[1] = b1;
        p1[2] = c1;
        p2[0] = a2;
        p2[1] = b2;
        p2[2] = c2;
        return pairing(p1, p2);
    }

    /// Convenience method for a pairing check for four pairs.
    function pairingProd4(
            G1Point memory a1, G2Point memory a2,
            G1Point memory b1, G2Point memory b2,
            G1Point memory c1, G2Point memory c2,
            G1Point memory d1, G2Point memory d2
    ) internal view returns (bool) {
        G1Point[] memory p1 = new G1Point[](4);
        G2Point[] memory p2 = new G2Point[](4);
        p1[0] = a1;
        p1[1] = b1;
        p1[2] = c1;
        p1[3] = d1;
        p2[0] = a2;
        p2[1] = b2;
        p2[2] = c2;
        p2[3] = d2;
        return pairing(p1, p2);
    }
}

contract Groth16Verifier {
    using Pairing for *;

    struct VerifyingKey {
        Pairing.G1Point alpha;
        Pairing.G2Point beta;
        Pairing.G2Point gamma;
        Pairing.G2Point delta;
        Pairing.G1Point[] gamma_abc;
    }

    struct Proof {
        Pairing.G1Point a;
        Pairing.G2Point b;
        Pairing.G1Point c;
    }

    /// @notice Returns the verification key
    /// @dev This is circuit-specific and would be generated during setup
    function verifyingKey() internal pure returns (VerifyingKey memory vk) {
        vk.alpha = Pairing.G1Point(
            // These would be actual values from trusted setup
            uint256(0x0000000000000000000000000000000000000000000000000000000000000001),
            uint256(0x0000000000000000000000000000000000000000000000000000000000000002)
        );
        vk.beta = Pairing.G2Point(
            [uint256(0x0000000000000000000000000000000000000000000000000000000000000001),
             uint256(0x0000000000000000000000000000000000000000000000000000000000000002)],
            [uint256(0x0000000000000000000000000000000000000000000000000000000000000003),
             uint256(0x0000000000000000000000000000000000000000000000000000000000000004)]
        );
        vk.gamma = Pairing.G2Point(
            [uint256(0x0000000000000000000000000000000000000000000000000000000000000005),
             uint256(0x0000000000000000000000000000000000000000000000000000000000000006)],
            [uint256(0x0000000000000000000000000000000000000000000000000000000000000007),
             uint256(0x0000000000000000000000000000000000000000000000000000000000000008)]
        );
        vk.delta = Pairing.G2Point(
            [uint256(0x0000000000000000000000000000000000000000000000000000000000000009),
             uint256(0x000000000000000000000000000000000000000000000000000000000000000a)],
            [uint256(0x000000000000000000000000000000000000000000000000000000000000000b),
             uint256(0x000000000000000000000000000000000000000000000000000000000000000c)]
        );

        // IC (gamma_abc) - one point per public input + 1
        vk.gamma_abc = new Pairing.G1Point[](3); // Example: 2 public inputs
        vk.gamma_abc[0] = Pairing.G1Point(
            uint256(0x000000000000000000000000000000000000000000000000000000000000000d),
            uint256(0x000000000000000000000000000000000000000000000000000000000000000e)
        );
        vk.gamma_abc[1] = Pairing.G1Point(
            uint256(0x000000000000000000000000000000000000000000000000000000000000000f),
            uint256(0x0000000000000000000000000000000000000000000000000000000000000010)
        );
        vk.gamma_abc[2] = Pairing.G1Point(
            uint256(0x0000000000000000000000000000000000000000000000000000000000000011),
            uint256(0x0000000000000000000000000000000000000000000000000000000000000012)
        );
    }

    /**
     * @notice Verify a Groth16 proof
     * @param a Proof component A
     * @param b Proof component B
     * @param c Proof component C
     * @param input Public inputs
     * @return r True if proof is valid
     */
    function verify(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory input
    ) public view returns (bool r) {
        Proof memory proof;
        proof.a = Pairing.G1Point(a[0], a[1]);
        proof.b = Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]);
        proof.c = Pairing.G1Point(c[0], c[1]);

        VerifyingKey memory vk = verifyingKey();

        require(input.length + 1 == vk.gamma_abc.length, "invalid-input-length");

        // Compute the linear combination vk_x
        Pairing.G1Point memory vk_x = Pairing.G1Point(0, 0);
        vk_x = Pairing.addition(vk_x, vk.gamma_abc[0]);

        for (uint i = 0; i < input.length; i++) {
            require(input[i] < Pairing.SCALAR_FIELD, "input-out-of-range");
            vk_x = Pairing.addition(vk_x, Pairing.scalar_mul(vk.gamma_abc[i + 1], input[i]));
        }

        // Verify the pairing equation:
        // e(A, B) = e(alpha, beta) * e(vk_x, gamma) * e(C, delta)
        //
        // Rearranged as:
        // e(A, B) * e(-vk_x, gamma) * e(-C, delta) = e(alpha, beta)
        //
        // Which is equivalent to checking:
        // e(-A, B) * e(vk_x, gamma) * e(C, delta) = e(alpha, beta)

        return Pairing.pairingProd4(
            Pairing.negate(proof.a), proof.b,
            vk_x, vk.gamma,
            proof.c, vk.delta,
            Pairing.negate(vk.alpha), vk.beta
        );
    }

    /**
     * @notice Convenience function for verifying with separate proof components
     */
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory input
    ) public view returns (bool) {
        return verify(a, b, c, input);
    }

    /// @notice Returns the scalar field modulus
    function SCALAR_FIELD() public pure returns (uint) {
        return 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    }
}

/**
 * Example usage contract
 */
contract PrivacyApplication {
    Groth16Verifier public verifier;

    event ProofVerified(address indexed prover, bool valid);

    constructor(address _verifier) {
        verifier = Groth16Verifier(_verifier);
    }

    /**
     * @notice Submit a proof for verification
     * @dev Users call this to prove something without revealing private data
     */
    function submitProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory publicInputs
    ) external {
        bool valid = verifier.verifyProof(a, b, c, publicInputs);

        require(valid, "Invalid proof");

        emit ProofVerified(msg.sender, valid);

        // Do something based on valid proof
        // e.g., mint NFT, transfer tokens, update state, etc.
    }

    /**
     * @notice Check if a proof is valid without state changes
     */
    function checkProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory publicInputs
    ) external view returns (bool) {
        return verifier.verifyProof(a, b, c, publicInputs);
    }
}
